-- Open Calls テストデータの挿入
INSERT INTO "open_calls" (
  "id",
  "title",
  "description",
  "imageUrl",
  "deadline",
  "startDate",
  "area",
  "organizer",
  "organizerType",
  "website",
  "targetArea",
  "targetAudience",
  "openCallType",
  "availableResources",
  "resourceType",
  "operatingCompany",
  "isActive",
  "createdAt",
  "updatedAt"
) VALUES 
(
  'open_call_001',
  'AI・データ活用による地域課題解決プロジェクト',
  '地域の課題をAI・データ技術で解決するスタートアップや企業を募集する公募です。',
  'https://example.com/images/ai-project.jpg',
  '2025-03-31 23:59:59',
  '2025-01-15 00:00:00',
  '全国',
  '総務省',
  '政府・自治体',
  'https://example.com/ai-project',
  'AI・データ活用、地域課題解決',
  'スタートアップ、中小企業、大学・研究機関',
  '公募・コンペ',
  '最大1000万円の支援金、専門家メンタリング',
  '資金支援、メンタリング',
  '総務省',
  true,
  NOW(),
  NOW()
),
(
  'open_call_002',
  'サステナブルテック・イノベーション・チャレンジ',
  '環境・社会課題の解決に向けたテクノロジーソリューションを募集します。',
  'https://example.com/images/sustainable-tech.jpg',
  '2025-04-30 23:59:59',
  '2025-02-01 00:00:00',
  '東京都',
  '東京都',
  '政府・自治体',
  'https://example.com/sustainable-tech',
  '環境技術、サステナビリティ、クリーンテック',
  'スタートアップ、中小企業、研究機関',
  '公募・コンペ',
  '最大500万円の支援金、展示会出展支援',
  '資金支援、展示会出展',
  '東京都',
  true,
  NOW(),
  NOW()
),
(
  'open_call_003',
  'ヘルステック・スタートアップ・アクセラレーター',
  '医療・ヘルスケア分野のイノベーションを支援するアクセラレータープログラムです。',
  'https://example.com/images/healthtech.jpg',
  '2025-05-15 23:59:59',
  '2025-03-01 00:00:00',
  '大阪府',
  '大阪府',
  '政府・自治体',
  'https://example.com/healthtech',
  'ヘルステック、医療、バイオテクノロジー',
  'スタートアップ、医療機関、研究機関',
  'アクセラレーター',
  '最大300万円の支援金、専門家ネットワーク',
  '資金支援、ネットワーキング',
  '大阪府',
  true,
  NOW(),
  NOW()
),
(
  'open_call_004',
  'スマートシティ・オープンイノベーション',
  '都市の課題を解決するスマートシティソリューションを募集します。',
  'https://example.com/images/smart-city.jpg',
  '2025-06-30 23:59:59',
  '2025-04-01 00:00:00',
  '神奈川県',
  '神奈川県',
  '政府・自治体',
  'https://example.com/smart-city',
  'スマートシティ、IoT、都市インフラ',
  'スタートアップ、中小企業、システムインテグレーター',
  '公募・コンペ',
  '最大800万円の支援金、実証実験支援',
  '資金支援、実証実験',
  '神奈川県',
  true,
  NOW(),
  NOW()
),
(
  'open_call_005',
  'フィンテック・イノベーション・チャレンジ',
  '金融サービスの革新を目指すフィンテックソリューションを募集します。',
  'https://example.com/images/fintech.jpg',
  '2025-07-31 23:59:59',
  '2025-05-01 00:00:00',
  '愛知県',
  '愛知県',
  '政府・自治体',
  'https://example.com/fintech',
  'フィンテック、決済、ブロックチェーン',
  'スタートアップ、金融機関、IT企業',
  '公募・コンペ',
  '最大600万円の支援金、金融機関とのマッチング',
  '資金支援、マッチング',
  '愛知県',
  true,
  NOW(),
  NOW()
);
